/* MILITOPO Orientación · v77-reset-seguro-wakelock-20260919 · PWA offline reforzada */
const MILITOPO_CACHE="militopo-v1-orientacion-v77-reset-seguro-wakelock-20260919";
const RUNTIME_CACHE="militopo-v1-orientacion-runtime-v77-reset-seguro-wakelock-20260919";
const CORE_ASSETS=["./","./index.html","./js/app.js","./js/app.js?v=v77-reset-seguro-wakelock-20260919","./js/live/live-phase2.js","./js/config/iof-symbols-f.js","./js/config/iof-symbols-baked.js","./js/config/plan-assets.js","./js/core/app-main.js","./js/pdf/pdf-professional.js","./js/results/results-v16.js","./js/results/results-classification-fix.js","./css/styles.css","./js/vendor/qr.js","./maps/index.json","./maps/valle-perdido.tif","./maps/el-valle-matizado.tif","./participante/","./participante/index.html","./participante/runner.html","./participante/styles.css","./participante/app.js","./participante/sw.js","./participante/manifest.webmanifest","./participante/icons/participante-192.png","./participante/icons/participante-512.png","./participante/icons/apple-touch-icon.png"];
const REMOTE_ASSETS=["https://unpkg.com/leaflet@1.9.4/dist/leaflet.css","https://unpkg.com/leaflet@1.9.4/dist/leaflet.js","https://unpkg.com/leaflet@1.9.4/dist/images/marker-icon.png","https://unpkg.com/leaflet@1.9.4/dist/images/marker-icon-2x.png","https://unpkg.com/leaflet@1.9.4/dist/images/marker-shadow.png","https://cdnjs.cloudflare.com/ajax/libs/proj4js/2.9.2/proj4.js","https://cdnjs.cloudflare.com/ajax/libs/jszip/3.10.1/jszip.min.js","https://cdnjs.cloudflare.com/ajax/libs/FileSaver.js/2.0.5/FileSaver.min.js","https://cdnjs.cloudflare.com/ajax/libs/jspdf/2.5.1/jspdf.umd.min.js","https://cdnjs.cloudflare.com/ajax/libs/html2canvas/1.4.1/html2canvas.min.js","https://cdn.jsdelivr.net/npm/geotiff@2.1.3/dist-browser/geotiff.min.js","https://cdn.jsdelivr.net/npm/jsqr@1.4.0/dist/jsQR.min.js","https://www.gstatic.com/firebasejs/12.15.0/firebase-app.js","https://www.gstatic.com/firebasejs/12.15.0/firebase-auth.js","https://www.gstatic.com/firebasejs/12.15.0/firebase-database.js"];
const TRUSTED_RUNTIME_ORIGINS=new Set(["https://unpkg.com","https://cdnjs.cloudflare.com","https://cdn.jsdelivr.net","https://raster.trailmap.fi","https://www.ign.es","https://tile.openstreetmap.org","https://www.gstatic.com"]);
async function cacheRemote(c,u){try{let r;try{r=await fetch(new Request(u,{mode:"cors",cache:"reload"}))}catch(_){r=await fetch(new Request(u,{mode:"no-cors",cache:"reload"}))}if(r)await c.put(u,r.clone())}catch(_){}}
async function trimCache(name,max=500){try{const c=await caches.open(name),keys=await c.keys();await Promise.all(keys.slice(0,Math.max(0,keys.length-max)).map(k=>c.delete(k)))}catch(_){}}
self.addEventListener("install",event=>{self.skipWaiting();event.waitUntil((async()=>{const c=await caches.open(MILITOPO_CACHE);await Promise.allSettled(CORE_ASSETS.map(u=>c.add(new Request(u,{cache:"reload"}))));await Promise.allSettled(REMOTE_ASSETS.map(u=>cacheRemote(c,u)))})())});
self.addEventListener("activate",event=>event.waitUntil((async()=>{if(self.registration.navigationPreload)try{await self.registration.navigationPreload.enable()}catch(_){}const keys=await caches.keys();await Promise.all(keys.filter(k=>(k.startsWith("militopo-v1-orientacion-")||k.startsWith("militopo-v1-page-snapshot-"))&&k!==MILITOPO_CACHE&&k!==RUNTIME_CACHE&&k!=="militopo-v1-page-snapshot-v77-reset-seguro-wakelock-20260919").map(k=>caches.delete(k)));await self.clients.claim()})()));
async function cached(req){return await caches.match(req,{ignoreSearch:false})}
self.addEventListener("fetch",event=>{const req=event.request;if(req.method!=="GET")return;const url=new URL(req.url),same=url.origin===self.location.origin,isRemote=TRUSTED_RUNTIME_ORIGINS.has(url.origin);if(!same&&!isRemote)return;event.respondWith((async()=>{const cache=await caches.open(same?MILITOPO_CACHE:RUNTIME_CACHE),hit=await cached(req),isNav=same&&req.mode==="navigate";if(hit&&!isNav){event.waitUntil(fetch(req).then(r=>{if(r&&r.status!==206)cache.put(req,r.clone()).catch(()=>{})}).catch(()=>{}));return hit}try{const preload=isNav?await event.preloadResponse:null,r=preload||await fetch(req);if(r&&r.status!==206){cache.put(req,r.clone()).catch(()=>{});if(!same)event.waitUntil(trimCache(RUNTIME_CACHE))}return r}catch(_){if(hit)return hit;if(isNav)return(await cached(new Request("./index.html")))||(await cached(new Request("./")))||new Response("<!doctype html><meta charset=utf-8><meta name=viewport content='width=device-width,initial-scale=1'><title>MILITOPO offline</title><body style='font-family:monospace;background:#10190b;color:#f5e6c8;padding:24px'><h1>MILITOPO sin cobertura</h1><p>El procedimiento y los datos guardados siguen disponibles. Los fondos de mapa no visitados pueden requerir conexión.</p></body>",{headers:{"Content-Type":"text/html;charset=utf-8"}});return new Response("",{status:503,statusText:"Offline"})}})())});
