/* MILITOPO Participante · v77-reset-seguro-wakelock-20260919 · progreso offline primero */
const CACHE_NAME="militopo-v1-participante-v77-reset-seguro-wakelock-20260919";
const RUNTIME_CACHE="militopo-v1-participante-runtime-v77-reset-seguro-wakelock-20260919";
const APP_SHELL=["./","./index.html","./runner.html","./styles.css","./styles.css?v=v77-reset-seguro-wakelock-20260919","./app.js","./app.js?v=v77-reset-seguro-wakelock-20260919","./manifest.webmanifest","./icons/participante-192.png","./icons/participante-512.png","./icons/apple-touch-icon.png","../js/live/live-phase2.js"];
const REMOTE_ASSETS=["https://cdn.jsdelivr.net/npm/jsqr@1.4.0/dist/jsQR.min.js","https://www.gstatic.com/firebasejs/12.15.0/firebase-app.js","https://www.gstatic.com/firebasejs/12.15.0/firebase-auth.js","https://www.gstatic.com/firebasejs/12.15.0/firebase-database.js"];
async function cacheRemote(c,u){try{let r;try{r=await fetch(new Request(u,{mode:"cors",cache:"reload"}))}catch(_){r=await fetch(new Request(u,{mode:"no-cors",cache:"reload"}))}if(r)await c.put(u,r.clone())}catch(_){}}
self.addEventListener("install",e=>{self.skipWaiting();e.waitUntil((async()=>{const c=await caches.open(CACHE_NAME);await Promise.allSettled(APP_SHELL.map(u=>c.add(new Request(u,{cache:"reload"}))));await Promise.allSettled(REMOTE_ASSETS.map(u=>cacheRemote(c,u)))})())});
self.addEventListener("activate",e=>e.waitUntil((async()=>{const names=await caches.keys();await Promise.all(names.filter(n=>n.startsWith("militopo-v1-participante-")&&n!==CACHE_NAME&&n!==RUNTIME_CACHE).map(n=>caches.delete(n)));await self.clients.claim()})()));
self.addEventListener("fetch",e=>{const req=e.request;if(req.method!=="GET")return;const url=new URL(req.url),same=url.origin===self.location.origin,trusted=url.origin==="https://cdn.jsdelivr.net"||url.origin==="https://www.gstatic.com";if(!same&&!trusted)return;e.respondWith((async()=>{const hit=(await caches.match(req,{ignoreSearch:false}));if(hit){e.waitUntil(fetch(req).then(async r=>{if(r&&r.status!==206){const c=await caches.open(same?CACHE_NAME:RUNTIME_CACHE);c.put(req,r.clone()).catch(()=>{})}}).catch(()=>{}));return hit}try{const r=await fetch(req);if(r&&r.status!==206){const c=await caches.open(same?CACHE_NAME:RUNTIME_CACHE);c.put(req,r.clone()).catch(()=>{})}return r}catch(_){if(req.mode==="navigate")return(await caches.match("./runner.html"))||(await caches.match("./index.html"))||(await caches.match("./"));return new Response("",{status:503,statusText:"Offline"})}})())});
