/* MILITOPO Participante · v2-f3a-runner-sessionfix-20260923 · progreso offline primero */
const CACHE_NAME="militopo-v2-participante-v2-f3a-runner-sessionfix-20260923";
const RUNTIME_CACHE="militopo-v2-participante-runtime-v2-f3a-runner-sessionfix-20260923";
const APP_SHELL=["./","./index.html","./runner.html","./styles.css","./styles.css?v=v2-f3a-runner-sessionfix-20260923","./app.js","./app.js?v=v2-f3a-runner-sessionfix-20260923","./manifest.webmanifest","./icons/participante-192.png","./icons/participante-512.png","./icons/apple-touch-icon.png","../js/live/live-phase2.js","../../js/v2/firebase-config.js","../../js/v2/bootstrap.js","../../js/v2/auth/roles.js","../../js/v2/auth/auth-ui.css?v=v2-f3a-runner-sessionfix-20260923","../../js/v2/auth/auth-ui.js?v=v2-f3a-runner-sessionfix-20260923","../../js/v2/data/invitation-inbox.js?v=v2-f3a-runner-sessionfix-20260923","../../js/v2/live/runner-session-v2.js?v=v2-f3a-runner-sessionfix-20260923"];
const REMOTE_ASSETS=["https://cdn.jsdelivr.net/npm/jsqr@1.4.0/dist/jsQR.min.js","https://www.gstatic.com/firebasejs/12.19.0/firebase-app.js","https://www.gstatic.com/firebasejs/12.19.0/firebase-auth.js","https://www.gstatic.com/firebasejs/12.19.0/firebase-database.js","https://www.gstatic.com/firebasejs/12.19.0/firebase-firestore.js","https://www.gstatic.com/firebasejs/12.19.0/firebase-functions.js"];
async function cacheRemote(c,u){try{let r;try{r=await fetch(new Request(u,{mode:"cors",cache:"reload"}))}catch(_){r=await fetch(new Request(u,{mode:"no-cors",cache:"reload"}))}if(r)await c.put(u,r.clone())}catch(_){}}
self.addEventListener("install",e=>{self.skipWaiting();e.waitUntil((async()=>{const c=await caches.open(CACHE_NAME);await Promise.allSettled(APP_SHELL.map(u=>c.add(new Request(u,{cache:"reload"}))));await Promise.allSettled(REMOTE_ASSETS.map(u=>cacheRemote(c,u)))})())});
self.addEventListener("activate",e=>e.waitUntil((async()=>{const names=await caches.keys();await Promise.all(names.filter(n=>n.startsWith("militopo-v2-participante-")&&n!==CACHE_NAME&&n!==RUNTIME_CACHE).map(n=>caches.delete(n)));await self.clients.claim()})()));
self.addEventListener("fetch",e=>{const req=e.request;if(req.method!=="GET")return;const url=new URL(req.url),same=url.origin===self.location.origin,trusted=url.origin==="https://cdn.jsdelivr.net"||url.origin==="https://www.gstatic.com";if(!same&&!trusted)return;e.respondWith((async()=>{const targetCache=await caches.open(same?CACHE_NAME:RUNTIME_CACHE);const isNav=same&&req.mode==="navigate";if(isNav){try{const r=await fetch(req);if(r&&r.status!==206)targetCache.put(req,r.clone()).catch(()=>{});return r}catch(_){return(await caches.match(req,{ignoreSearch:true}))||(await caches.match("./index.html"))||(await caches.match("./runner.html"))||(await caches.match("./"));}}const hit=await caches.match(req,{ignoreSearch:false});if(hit){e.waitUntil(fetch(req).then(r=>{if(r&&r.status!==206)targetCache.put(req,r.clone()).catch(()=>{})}).catch(()=>{}));return hit}try{const r=await fetch(req);if(r&&r.status!==206)targetCache.put(req,r.clone()).catch(()=>{});return r}catch(_){return new Response("",{status:503,statusText:"Offline"})}})())});
